version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE-URL: ${TEST_DB}
    command: npm run start
    volumes:
      - .:/app/
      - /app/node_modules
  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB-USER-NAME}
      POSTGRES_PASSWORD: ${DB-PASS}
      POSTGRES_DB: ${DATABASE-URL}
